import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [countdownSeconds, setCountdownValue] = useState(9);

  useEffect(() => {
    const intervalId = setInterval(() => {
      if (countdownSeconds > 0) {
        setCountdownValue(countdownSeconds - 1);
        return;
      }
      alert('le van jarva halo');
      clearInterval(intervalId);
    }, 1000);

    return () => clearInterval(intervalId);
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {countdownSeconds}
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
